Add features related to PAPU undulator
lnls-ima/insertion-devices pull request #37
Opened 2023-03-02 20:44 UTC by lucashfrancisco

This adds the following modifications related to the a Prototype Adjustable Phase Undulator:

- New `PAPU` class in `models` module and corresponding block shapes at the `block` module.
- A modification in the `APU` class allowing for different block shapes for the upper and lower cassettes, necessary for deriving the new `PAPU` class.
- A new [example notebook](https://github.com/lnls-ima/insertion-devices/blob/8d8a923daac6f2d441d83371f6031c61a783cf30/examples/PAPU.ipynb) has been added, defining the PAPU undulator using the `APU` class.
- New options for selecting blocks for shimming inside a cassette:
    - `vlf` : vertical blocks and "forward pointing" (z+) longitudinal blocks.
    - `all` : all blocks.
- The option of using a different block selection for each cassette was added, what is given in a dictionary relating each cassette to its block set (e.g. `block_type = {'cse':'v', 'cie':'vpos'}`)

2023-03-03 11:42 UTC, fernandohds564 approved these changes

2023-03-03 12:09 UTC, Gabrielrezende-asc approved these changes

2023-03-03 12:12 UTC, FernandaMenicucci approved these changes

2023-03-06 12:52 UTC, Gabrielrezende-asc requested changes
Hey guys, setting the new gap (23. 4 mm to give a field amplitude of 0.45 T) as the default value should be a good idea. The default gap value now is 8.0 mm, but the default shift set centralizes the field for 23.4 mm, so, to keep consistency we should also change the gap.
I don't know the exact value you are considering for the new gap, 23.4 mm is the value I found in my calculations, please correct me if I am wrong.

2023-03-07 11:44 UTC, Gabrielrezende-asc approved these changes

2023-03-07 11:55 UTC, merged